-- migrate:up
CREATE TABLE posts (
  title VARCHAR(100) NOT NULL,
  content VARCHAR(3000) NOT NULL,
  user_id INT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP
);

-- migrate:down
DROP TABLE posts;

